version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.8
    working_directory: ~/terraform
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run: 
          command: terraform get -update=true # 現状のSourceだと不要
          working_directory: ~/terraform/sample/ec2
      - run:
          name: planing at terraform
          command: |
            if [ `expr "${CIRCLE_BRANCH}" : "develop"` -gt 0 ]; then
              terraform init
              terraform plan
            fi 
          working_directory: ~/terraform/sample/ec2
      - deploy:
          name: deploy at terraform
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              terraform init
              terraform plan
              # terraform apply 
            fi 
          working_directory: ~/terraform/sample/ec2